# Generated by Django 2.2.2 on 2021-03-03 00:09

from django.db import migrations, models
import django.db.models.deletion


def set_trial(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Pose = apps.get_model('data_collection', 'Pose')
    i=0
    all_poses = Pose.objects.all()
    for pose in all_poses:
        i = i + 1
        if i % 10 == 0:
            print(i)
        # default ordering for events is desc start_datetime
        events = pose.events.all()
        if not events:
            continue
        pose.trial = events[0].trial
        pose.save()



def reverse_func(apps, schema_editor):
    # don't need to do anything for reversing the addition of a field
    pass  


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='data_collection.Trial'),
        ),
        migrations.RunPython(set_trial, reverse_func),
    ]
