# Generated by Django 2.2.2 on 2021-03-31 21:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_pose_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('key_point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('z_layer', models.FloatField()),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='data_collection.RegionType')),
                ('scenarios', models.ManyToManyField(blank=True, related_name='regions', to='data_collection.Scenario')),
            ],
        ),
    ]
