# Generated by Django 2.2.2 on 2021-04-26 06:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0004_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityEventRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('metadata_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='unfound_entities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='EntityEventRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.Entity')),
                ('entity_event_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.EntityEventRole')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_entities', to='data_collection.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='entities',
            field=models.ManyToManyField(related_name='associated_events', through='data_collection.EntityEventRelation', to='data_collection.Entity'),
        ),
    ]
