# Generated by Django 2.2.2 on 2021-05-24 22:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0005_entity_event_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pose',
            name='velocity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
    ]
