# Generated by Django 3.2.13 on 2022-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0008_entity_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invalid_entities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='unfound_entities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='requesteddata',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
