# Generated by Django 3.2.13 on 2022-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptedevent',
            name='add_event_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
