"""
This
"""
from data_collection.factories import factories
from automation.factories import factories as auto_factories

viewset_to_factory = {
    "user": factories.UserFactory,
    "userprofile": factories.UserProfileFactory,
    "role": factories.RoleFactory,
    "tester": factories.TesterFactory,
    "pointstyle": factories.PointStyleFactory,
    "entitytype": factories.EntityTypeFactory,
    "entity": factories.EntityFactory,
    "entityeventrole": factories.EntityEventRoleFactory,
    "entitygroup": factories.EntityGroupFactory,
    "entitystate": factories.EntityStateFactory,
    "capability": factories.CapabilityFactory,
    "location": factories.LocationFactory,
    "campaign": factories.CampaignFactory,
    "trial": factories.TrialFactory,
    "weather": factories.WeatherFactory,
    "testcondition": factories.TestConditionFactory,
    "performer": factories.PerformerFactory,
    "testmethod": factories.TestMethodFactory,
    "scenario": factories.ScenarioFactory,
    "capabilityundertest": factories.CapabilityUnderTestFactory,
    "systemconfiguration": factories.SystemConfigurationFactory,
    "posesource": factories.PoseSourceFactory,
    "pose": factories.PoseFactory,
    "eventlevel": factories.EventLevelFactory,
    "eventtype": factories.EventTypeFactory,
    "event": factories.EventFactory,
    "segment": factories.SegmentFactory,
    "note": factories.NoteFactory,
    "imagetype": factories.ImageTypeFactory,
    "servertype": factories.ServerTypeFactory,
    "serverparam": factories.ServerParamFactory,
    "server": factories.ServerFactory,
    "trigger": factories.TriggerFactory,
    "conditionvariable": factories.ConditionVariableFactory,
    "requesteddata": factories.RequestedDataFactory,
    "querysetspecification": factories.QuerySetSpecificationFactory,
    "querysetmethod": factories.QuerySetMethodFactory,
    "extractionfield": factories.ExtractionFieldFactory,
    "extractionspecification": factories.ExtractionSpecificationFactory,
    "clockphase": factories.ClockPhaseFactory,
    "clockconfig": factories.ClockConfigFactory,
    "regiontype": factories.RegionTypeFactory,
    "region": factories.RegionFactory,
    "script": auto_factories.ScriptFactory,
    "scriptedevent": auto_factories.ScriptedEventFactory,
    "scriptcondition": auto_factories.ScriptConditionFactory,
}
